config/routes.rb
Rails.application.routes.draw do
  resources :weeks

  root 'main#index'
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  match 'register_participant', to: 'main#register_participant', as: 'register_participant', via: [:get]
  match 'edit_participant', to: 'main#edit_participant', as: 'edit_participant', via: [:get]
  match 'update_participant', to: 'main#update_participant', as: 'update_participant', via: [:post]
  match 'set_inactive', to: 'main#set_inactive', as: 'set_inactive', via: [:post]
  match 'mark_got_shirt', to: 'main#mark_got_shirt', as: 'mark_got_shirt', via: [:post]
  match 'save_new_participant', to: 'main#save_new_participant', as: 'save_new_participant', via: [:post, :get]
  match 'list_participants', to: 'main#list_participants', as: 'list_participants', via: [:get]
  match 'search_by_name', to: 'main#search_by_name', as: 'search_by_name', via: [:get, :post]
  match 'search_by_card', to: 'main#search_by_card', as: 'search_by_card', via: [:get, :post]
  match 'load_report_interface', to: 'main#load_report_interface', as: 'load_report_interface', via: [:get, :post]
  match 'record_minutes', to: 'main#record_minutes', as: 'record_minutes', via: [:get, :post]
  match 'stats', to: 'main#stats', as: 'stats', via:[:get, :post]
  match 'get_eg_data', to: 'main#get_eg_data', as: 'get_eg_data', via:[:get, :post]
  match 'shirt_stats', to: 'main#shirt_stats', as: 'shirt_stats', via:[:get, :post]
  match 'weekly_reports', to: 'main#weekly_reports', as: 'weekly_reports', via:[:get, :post]
  match 'final_reports', to: 'main#final_reports', as: 'final_reports', via:[:get, :post]
  match 'send_to_school_report', to: 'main#send_to_school_report', as: 'send_to_school_report', via:[:get, :post]
  match 'leaders', to: 'main#leaders', as: 'leaders', via:[:get, :post]
  match 'patron_check_for_participants', to: 'main#patron_check_for_participants', as: 'check_for_participants', via: [:get, :post]
  match 'patron_show_participants', to: 'main#patron_show_participants', as: 'patron_show_participants', via: [:get, :post]
  match 'patron_load_report_interface', to: 'main#patron_load_report_interface', as: 'patron_load_report_interface', via:[:get, :post]
  match 'patron_register_participant', to: 'main#patron_register_participant', as: 'patron_register_participant', via:[:get, :post]
  match 'school_totals_report', to: 'main#school_totals_report', as: 'school_totals_report', via:[:get, :post]
  match 'year_end_reports', to: 'main#year_end_reports', as: 'year_end_reports', via:[:get, :put]
  match 'registrations_report', to: 'main#registrations_report', as: 'registrations_report', via:[:get, :put]
  

end

app/models/week.rb
class Week < ActiveRecord::Base
end

app/controllers/weeks_controller.rb
class WeeksController < ApplicationController
  before_action :set_week, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!
  # GET /weeks.json
  def index
    @weeks = Week.all
  end

  # GET /weeks/1
  # GET /weeks/1.json
  def show
  end

  # GET /weeks/new
  def new
    @week = Week.new
  end

  # GET /weeks/1/edit
  def edit
  end

  # POST /weeks
  # POST /weeks.json
  def create
    @week = Week.new(week_params)

    respond_to do |format|
      if @week.save
        format.html { redirect_to @week, notice: 'Week was successfully created.' }
        format.json { render :show, status: :created, location: @week }
      else
        format.html { render :new }
        format.json { render json: @week.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weeks/1
  # PATCH/PUT /weeks/1.json
  def update
    respond_to do |format|
      if @week.update(week_params)
        format.html { redirect_to @week, notice: 'Week was successfully updated.' }
        format.json { render :show, status: :ok, location: @week }
      else
        format.html { render :edit }
        format.json { render json: @week.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weeks/1
  # DELETE /weeks/1.json
  def destroy
    @week.destroy
    respond_to do |format|
      format.html { redirect_to weeks_url, notice: 'Week was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_week
      @week = Week.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def week_params
      params.require(:week).permit(:name, :start_date, :end_date)
    end
end

app/helpers/weeks_helper.rb
module WeeksHelper
end

app/views/weeks/_form.html.erb
<%= form_for(@week) do |f| %>
  <% if @week.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@week.errors.count, "error") %> prohibited this week from being saved:</h2>

      <ul>
      <% @week.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.date_select :end_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/weeks/edit.html.erb
<h1>Editing Week</h1>

<%= render 'form' %>

<%= link_to 'Show', @week %> |
<%= link_to 'Back', weeks_path %>

app/views/weeks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Weeks</h1>
<div style="max-width: 600px">
<div class="row">
  <div class="col-xs-3"><b>Name</b></div>
  <div class="col-xs-3"><b>Start Date</b></div>
  <div class="col-xs-3"><b>End Date</b></div>
  <div class="col-xs-3"><b>Options</b></div>
</div>

<% @weeks.each do |week| %>
  <div class="row" style="border-bottom: 1px dashed #000">
    <div class="col-xs-3"><%= week.name %></div>
    <div class="col-xs-3"><%= week.start_date.strftime("%A %b %d") %></div>
    <div class="col-xs-3"><%= week.end_date.strftime("%A %b %d") %></div>
    <div class="col-xs-3">
      |<%= link_to 'Edit', edit_week_path(week) %>|
      |<%= link_to 'Destroy', week, method: :delete, data: { confirm: 'Are you sure?' } %>|
    </div>
  </div>
<% end %>
</div>
<br>

<%= link_to 'Create New Week', new_week_path %>

app/views/weeks/new.html.erb
<h1>New Week</h1>

<%= render 'form' %>

<%= link_to 'Back', weeks_path %>

app/views/weeks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @week.name %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @week.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @week.end_date %>
</p>

<%= link_to 'Edit', edit_week_path(@week) %> |
<%= link_to 'Back', weeks_path %>